"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificatorService = exports.NotificatorServiceSchema = exports.NotifyResponseSchema = exports.NotifyRequestSchema = exports.file_yuxsr_dev_pb_v1_notificator = void 0;
var notificator_pb_1 = require("./gencode/ts/yuxsr_dev_pb/v1/notificator_pb");
Object.defineProperty(exports, "file_yuxsr_dev_pb_v1_notificator", { enumerable: true, get: function () { return notificator_pb_1.file_yuxsr_dev_pb_v1_notificator; } });
Object.defineProperty(exports, "NotifyRequestSchema", { enumerable: true, get: function () { return notificator_pb_1.NotifyRequestSchema; } });
Object.defineProperty(exports, "NotifyResponseSchema", { enumerable: true, get: function () { return notificator_pb_1.NotifyResponseSchema; } });
Object.defineProperty(exports, "NotificatorServiceSchema", { enumerable: true, get: function () { return notificator_pb_1.NotificatorService; } });
var notificator_connect_1 = require("./gencode/ts/yuxsr_dev_pb/v1/notificator_connect");
Object.defineProperty(exports, "NotificatorService", { enumerable: true, get: function () { return notificator_connect_1.NotificatorService; } });
