// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file yuxsr_dev_pb/v1/notificator.proto (package yuxsr_dev_pb.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { NotifyRequest, NotifyResponse } from "./notificator_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service yuxsr_dev_pb.v1.NotificatorService
 */
export const NotificatorService = {
  typeName: "yuxsr_dev_pb.v1.NotificatorService",
  methods: {
    /**
     * @generated from rpc yuxsr_dev_pb.v1.NotificatorService.Notify
     */
    notify: {
      name: "Notify",
      I: NotifyRequest,
      O: NotifyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

