// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file yuxsr_dev_pb/v1/notificator.proto (package yuxsr_dev_pb.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yuxsr_dev_pb/v1/notificator.proto.
 */
export const file_yuxsr_dev_pb_v1_notificator: GenFile = /*@__PURE__*/
  fileDesc("CiF5dXhzcl9kZXZfcGIvdjEvbm90aWZpY2F0b3IucHJvdG8SD3l1eHNyX2Rldl9wYi52MSIgCg1Ob3RpZnlSZXF1ZXN0Eg8KB21lc3NhZ2UYASABKAkiEAoOTm90aWZ5UmVzcG9uc2UyXwoSTm90aWZpY2F0b3JTZXJ2aWNlEkkKBk5vdGlmeRIeLnl1eHNyX2Rldl9wYi52MS5Ob3RpZnlSZXF1ZXN0Gh8ueXV4c3JfZGV2X3BiLnYxLk5vdGlmeVJlc3BvbnNlQsUBChNjb20ueXV4c3JfZGV2X3BiLnYxQhBOb3RpZmljYXRvclByb3RvUAFaR2dpdGh1Yi5jb20veXV4c3IveXV4c3JfZGV2X3BiL2dlbmNvZGUvZ28veXV4c3JfZGV2X3BiL3YxO3l1eHNyX2Rldl9wYnYxogIDWVhYqgINWXV4c3JEZXZQYi5WMcoCDVl1eHNyRGV2UGJcVjHiAhlZdXhzckRldlBiXFYxXEdQQk1ldGFkYXRh6gIOWXV4c3JEZXZQYjo6VjFiBnByb3RvMw");

/**
 * @generated from message yuxsr_dev_pb.v1.NotifyRequest
 */
export type NotifyRequest = Message<"yuxsr_dev_pb.v1.NotifyRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message yuxsr_dev_pb.v1.NotifyRequest.
 * Use `create(NotifyRequestSchema)` to create a new message.
 */
export const NotifyRequestSchema: GenMessage<NotifyRequest> = /*@__PURE__*/
  messageDesc(file_yuxsr_dev_pb_v1_notificator, 0);

/**
 * @generated from message yuxsr_dev_pb.v1.NotifyResponse
 */
export type NotifyResponse = Message<"yuxsr_dev_pb.v1.NotifyResponse"> & {
};

/**
 * Describes the message yuxsr_dev_pb.v1.NotifyResponse.
 * Use `create(NotifyResponseSchema)` to create a new message.
 */
export const NotifyResponseSchema: GenMessage<NotifyResponse> = /*@__PURE__*/
  messageDesc(file_yuxsr_dev_pb_v1_notificator, 1);

/**
 * @generated from service yuxsr_dev_pb.v1.NotificatorService
 */
export const NotificatorService: GenService<{
  /**
   * @generated from rpc yuxsr_dev_pb.v1.NotificatorService.Notify
   */
  notify: {
    methodKind: "unary";
    input: typeof NotifyRequestSchema;
    output: typeof NotifyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_yuxsr_dev_pb_v1_notificator, 0);

