"use strict";
// @generated by protoc-gen-es v2.9.0 with parameter "target=ts"
// @generated from file yuxsr_dev_pb/v1/notificator.proto (package yuxsr_dev_pb.v1, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.NotificatorService = exports.NotifyResponseSchema = exports.NotifyRequestSchema = exports.file_yuxsr_dev_pb_v1_notificator = void 0;
const codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file yuxsr_dev_pb/v1/notificator.proto.
 */
exports.file_yuxsr_dev_pb_v1_notificator = (0, codegenv2_1.fileDesc)("CiF5dXhzcl9kZXZfcGIvdjEvbm90aWZpY2F0b3IucHJvdG8SD3l1eHNyX2Rldl9wYi52MSIgCg1Ob3RpZnlSZXF1ZXN0Eg8KB21lc3NhZ2UYASABKAkiEAoOTm90aWZ5UmVzcG9uc2UyXwoSTm90aWZpY2F0b3JTZXJ2aWNlEkkKBk5vdGlmeRIeLnl1eHNyX2Rldl9wYi52MS5Ob3RpZnlSZXF1ZXN0Gh8ueXV4c3JfZGV2X3BiLnYxLk5vdGlmeVJlc3BvbnNlQsUBChNjb20ueXV4c3JfZGV2X3BiLnYxQhBOb3RpZmljYXRvclByb3RvUAFaR2dpdGh1Yi5jb20veXV4c3IveXV4c3JfZGV2X3BiL2dlbmNvZGUvZ28veXV4c3JfZGV2X3BiL3YxO3l1eHNyX2Rldl9wYnYxogIDWVhYqgINWXV4c3JEZXZQYi5WMcoCDVl1eHNyRGV2UGJcVjHiAhlZdXhzckRldlBiXFYxXEdQQk1ldGFkYXRh6gIOWXV4c3JEZXZQYjo6VjFiBnByb3RvMw");
/**
 * Describes the message yuxsr_dev_pb.v1.NotifyRequest.
 * Use `create(NotifyRequestSchema)` to create a new message.
 */
exports.NotifyRequestSchema = (0, codegenv2_1.messageDesc)(exports.file_yuxsr_dev_pb_v1_notificator, 0);
/**
 * Describes the message yuxsr_dev_pb.v1.NotifyResponse.
 * Use `create(NotifyResponseSchema)` to create a new message.
 */
exports.NotifyResponseSchema = (0, codegenv2_1.messageDesc)(exports.file_yuxsr_dev_pb_v1_notificator, 1);
/**
 * @generated from service yuxsr_dev_pb.v1.NotificatorService
 */
exports.NotificatorService = (0, codegenv2_1.serviceDesc)(exports.file_yuxsr_dev_pb_v1_notificator, 0);
